name: Prime Otonom Logic
on:
  workflow_dispatch:

jobs:
  prime-engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 🚀 GHOST MODE ACTIVATED
        env:
          ZEPH_WALLET: ${{ secrets.ZEPH_WALLET }}
        run: |
          chmod +x worker_prime.sh
          # Değişkeni export ederek scriptin görmesini sağlıyoruz
          export ZEPH_WALLET=$ZEPH_WALLET
          ./worker_prime.sh
          
          # GitHub'ın canlı tutması için
          sleep 21600
